[workspace]
# This should only list projects that are not
# in the dependency tree in any other way
members = [
    "consensus",
    # "comm", (WIP: Do not enable unless testing)
    # RBC module
    "node",
]
